### ISSUE TITLE
[Request] Run once at start option

### ISSUE THREAD

**Issue by Pikachews** [bfriesen/RandomSkunk.Hosting.Cron#1]
👋 Hi there! Thanks for creating this package!

Funny coincidence, I actually just started a small project where I added cron capabilities to a project using a HostedService, and after finishing the project, I thought to myself "I wonder if someone built (this exact package)" then I found this on NuGet, and it seems to be a relatively new publish!

Anyways, back to my main point: would it be possible to add an option to run once at start, regardless of the next scheduled cron time?

Thanks again!

**Comment by bfriesen** [comment]
Sorry, I just today noticed this issue. I've added a `RunAtStartup` setting (default value is false) that lets you do this. Use the version I just published, [2.1.0](https://www.nuget.org/packages/RandomSkunk.Hosting.Cron/2.1.0).
